name: Publish Docker images

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Store tag in environment file
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Build and push backend Docker image
      - name: Build & push backend Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          context: ../../back
          file: ../../back/Dockerfile
          image: safaeank/smarthopitalback
          tags: latest, ${{ env.TAG }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push frontend Docker image
      - name: Build & push frontend Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          context: ../../front
          file: ../../front/Dockerfile
          image: safaeank/smarthopitalfront
          tags: latest, ${{ env.TAG }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}